### ISSUE TITLE
Regression making menus unusable

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1137] opened 2021-01-29 22:59 UTC
I'm having terrible problems with menus in the latest McCLIM. I've tried both mcclim-20210124-git via Quicklisp, and also a git clone of master from earlier today; and I've tried them on Linux and macOS. All have similar behaviour. I'm running with `clim:*default-server-path* :clx-ttf` - in contrast, the unlovely `:clx` works fine.

In `(clim-demo:demodemo)` when I run tests that include menus, here's what happens:

Gadget Test, Menu Test

- CLX outputs a warning message every time the mouse moves from one menu item to another
- After moving the mouse out of a menu item, the item fails to unhighlight
- After 2nd level sub-menus pop up, they sometimes disappear as soon as the mouse is moved into them

Accepting Values Test

- Menu items in the Menu Choose 1-4 and Accept Popup menus sometimes highlight when the mouse moves over them and sometimes don't

Here are the warning messages:

Ubuntu 3.19.0-79-generic
```
WARNING:
   Received CLX UNKNOWN-ERROR (139) in process #<MCCLIM-TRUETYPE::CLX-TTF-PORT :HOST "" :DISPLAY-ID 0 {1004E77BA3}>'s event process.
WARNING:
   Received CLX UNKNOWN-ERROR (139) in process main thread for display #<DISPLAY :0 (The X.Org Foundation R11501000)>.
```

macOS 10.14.6 / XQuartz 2.7.11
```
WARNING:
   Received CLX UNKNOWN-ERROR (141) in process #<MCCLIM-TRUETYPE::CLX-TTF-PORT :HOST "private/tmp/com.apple.launchd.xzTx4AXOiz/org.macosforge.xquartz" :DISPLAY-ID 0 {10037E4753}>'s event process.
WARNING:
   Received CLX UNKNOWN-ERROR (141) in process main thread for display #<DISPLAY private/tmp/com.apple.launchd.xzTx4AXOiz/org.macosforge.xquartz:0 (The X.Org Foundation R11804000)>.
```

I'm afraid I don't know where to start to fix this.

**Comment by dkochmanski** [comment] 2021-01-30 07:58
Thanks, the issue is fixed in backend-manual branch, but the branch is not finished yet, so I'm simply disabling xrender drawing of rectangles. The problem should be gone now.

**Closed by dkochmanski** 2021-01-30 07:58 UTC
