### ISSUE TITLE
bug: (setf frame-command-table)

### ISSUE THREAD

**Issue by gas2serra** [McCLIM/McCLIM#21] opened 2016-03-02 14:44 UTC
Changing the frame’s command table does NOT redisplay, and rebuild, the menu bar.

From spec:

> (setf frame-command-table) command-table frame   [Generic Function]
> Sets the command table for the frame frame to command-table. Changing the frame’s command
> table will redisplay the command menus (or menu bar) as needed.

**Comment by dkochmanski** [comment] 2016-08-16 09:14
This bug has assigned a 100$ bounty: https://www.bountysource.com/teams/mcclim/bounties

**Comment by gabriel-laddel** [comment] 2016-08-16 09:16
Wouldja stop being useless already and assign bounties to the parts of the project that are ~ difficult ~ to solve?

@robert-strandh thoughts?

**Comment by nsrahmad** [comment] 2017-04-08 04:32
## Recreating the bug

The easiest way to reproduce the bug is to use `clim-listener` (it has all we need; Menu bar and REPL). Load the clim-listener and execute following code.

1.  Copy the current active command-table and modify it.

```lisp
    (defparameter *new-commnad-table* (frame-command-table *application-frame*))

    (add-menu-item-to-command-table *new-command-table* "Dummy" :divider :label)
```
1.  Now set the frame command-table to *new-command-table*.

```lisp
    (setf (frame-command-table *application-frame*) *new-command-table*)
```

According to the spec, this last step should have updated the menu-bar with our new menu item.

## What is the problem?

To understand the problem, You need to first understand how McClim creates the menu bar. 

-   When McClim starts creating the application-frame, It first builds the menu bar and hard-wires it to the top of the frame.
-   Then it creates every other panes and adds them to the frame.
-   Even if we change the contents of menu bar, We just can’t repaint or rebuild the menu bar. Being hard-wired to the frame on creation, It cannot be updated independently.
-   Only way to solve the problem is to regenerate the whole frame, which will build the menu bar again.

Luckily, McClim provides the method (generate-panes) that does just that.

## Problem with `generate-panes`

So to solve the problem, you just need to create an `:after` method to `(setf (frame-command-table))` method, which calls the `generate-panes`. Doing that actually works but there seems to be a problem. `generate-panes` should not be clearing the whole output history in the clim-listener pane. Fortunately, Just looking at the git log, I found the commit a74e3960b9bffb9 by @dkochmanski , which fixed “generate-panes repainting problem” by creating every pane from scratch. That’s not the way to solve this problem.

## Fixing `generate-panes`

The problem is in `:after` method of `generate-panes`, which is responsible to allocate space for `frame-top-level-sheet`. The method used is to get the current geometry of frame, set the sheet-region, make bounding rectangle and then call `allocate-space` with new width and height. Here `compose-space` is called which returns the current space requirements to `allocate-space`.

`compose-space` seems to cache the value and returns the same value even if the requirements have changed. It will return new values only if `note-space-requirements-changed` have signaled. And `note-space-requirements-changed` is called in `:after` method of `change-space-requirements`.

To fix the problem, we need to call `change-space-requirements` before setting sheet-region and calling allocate-space. Adding this call fixes the `generate-panes` and it should fix #146.

Now calling `generate-panes` either to change a layout or to update the menu-bar will not clear the existing data on panes.

## Updating Menu bar after changes

Since `frame-command-table` is an accessor, we can define auxiliary methods to call `generate-panes` which will update menu-bar. But It turned out not to be this simple, `(setf frame-command-table)` is called
1.  when `accpting-values` dialog is called, it replaces `frame-command-table` with it’s own command-table (this command-table has some commands, keystrokes but no menu items (the achilles' heel  :simple_smile:).
2.  when `accpeting-values` dialog is closed, `accepting-values-command-table` is again replaced by the frame-command-table. these two calls happen independently.
3.  When someone updates the command-table and possibly menu-items in it, and want the changes to take effect immediately.

To fix it, we need a little complicated `:around` method which can inspect its arguments before calling any primary method. 

1.  If the `new-command-table` has no menu-items (case 1) you can just (call-next-method).
2.  But in case 2, `new-command-table` has the menu-bar, so how can we avoid it. The solution is to look what the existing command-table looks like. if this is getting called after `accepting-values` has entered (case 2), `current-command-table` will not have menu-items! Remember we are checking it before replacing the command-table, so we can decide to call-next-method and do nothing else.
3.  For any other case, we call-next-method and then call generate-panes. We need here a temporary variable to hold the return-value of `call-next-method` to return it as return-value of the `(setf frame-command-table)` call, just to make this `:around` method totally transparent.

With this changes, you can check if the problem is fixed. In my testing, this fixes it.

**Comment by dkochmanski** [comment] 2019-10-24 07:20
This is still the issue, menu-bar is not redisplayed. Please try "Extend things" (works), and "Extend menu" (doesn't work).

```common-lisp
(defpackage #:menutest
  (:use :clim :clim-extensions :clim-lisp)
  (:export #:menutest))

(in-package #:menutest)

(define-application-frame menutest ()
  ()
  (:menu-bar menubar-command-table)
  (:panes
   (screen :application
           :display-time nil
           :text-style (make-text-style :sans-serif :roman :normal)))
  (:layouts
   (defaults (vertically () screen))))

(define-menutest-command com-extend-things ((name string))
  (add-menu-item-to-command-table 'things-command-table name :divider t)
  (format *standard-output* "You've added ~s to ~s." name "Things")
  (finish-output *standard-output*))

(define-menutest-command com-extend-menu ()
  (add-menu-item-to-command-table 'menubar-command-table "Help" :command 'com-help)
  (format *standard-output* "You've added Help to the Menubar.~%")
  (finish-output *standard-output*))

(define-menutest-command com-help ()
  (format *standard-output* "You pressed the Help button.~%")
  (finish-output *standard-output*))

(define-menutest-command com-file ()
  (format *standard-output* "You pressed the File button.~%")
  (finish-output *standard-output*))

(define-menutest-command com-kenobi ()
  (format *standard-output* "You pressed the General Kenobi button.~%")
  (finish-output *standard-output*))

(define-menutest-command com-konichiwa ()
  (format *standard-output* "You pressed the Konichiwa button.~%")
  (finish-output *standard-output*))

(define-menutest-command com-hi ()
  (format *standard-output* "You pressed the Hi button.~%")
  (finish-output *standard-output*))

(make-command-table 'kenobi-command-table
                    :errorp nil
                    :menu '(("General Kenobi" :command com-kenobi)
                            ("Konichiwa"      :command com-konichiwa)))

(make-command-table 'buffer-command-table
		    :errorp nil
		    :menu '(("Hello there" :menu kenobi-command-table)
			    ("Hi there"    :command com-hi)))

(make-command-table 'things-command-table
		    :errorp nil
		    :menu '(("Extend things" :command com-extend-things)
                            ("Extend menu"   :command com-extend-menu)))

(make-command-table 'menubar-command-table
		    :errorp nil
		    :menu '(("Buffer" :menu buffer-command-table)
			    ("File"   :command com-file)
                            ("Things" :menu things-command-table)))
```

**Comment by nsrahmad** [comment] 2019-11-13 17:51
Hi,
The problem is with menu items placed on the menu-bar. They are attached to frame upon frame creation time (look in Core/clim-core/frame.lisp). sub-menus are created at run-time, so there is no problem with sub-menus.

My solution was to call `generate-panes` on frame. it preserves the frame contents and re-creates the frame. However, it is expensive to call. Try putting `(generate-panes *default-frame-manager* *application-frame*)` in `com-extend-menu` after changing menu bar. I thought this solution was fine as it is called rarely anyway.

Or so we thought until one day, gas2serra found ESA changes the command table of the frame on every single key-press! gas2serra removed call to `generate-panes` with https://github.com/McCLIM/McCLIM/pull/230 .This looks alright on first look, but misses the part that it is not enough to trigger a re-layout. sub-menus will be updated but you can't change the menu items on menu bar iteself.

Proper solution will be to refactor menu bar implementation so that it respects the standard pane and layout protocols. but it is a big undertaking with very little real gain.

Another way would be to try to detect when top-level menu items are changing and only then call `generate-panes`. This is proving really difficult to detect, and I always end up with redundant calls to `generate-panes`.

Or we could provide a function to manually re-generate menu bar after modifying menu bar, documenting it as current implementation's limitation.

**Comment by dkochmanski** [comment] 2019-11-13 18:00
I'm not sure how viable it is, but we may consider calling generate-panes like we did before and make ESA less chatty.

**Comment by nsrahmad** [comment] 2019-11-14 04:48
No, that is not viable. This is the most natural way for ESA to implement Emacs "self-inserting commands".

**Comment by dkochmanski** [comment] 2020-12-10 14:44
fixed in master.

**Closed by dkochmanski** 2020-12-10 14:44 UTC
Labels: bug
