### ISSUE TITLE
clim-demo experiences a strange error on the i3 window manager

### ISSUE THREAD

**Issue by SlightlyCyborg** [McCLIM/McCLIM#690] opened 2019-01-24 04:22 UTC
[Here](https://gfycat.com/CourageousLegitimateBluet) is a video of the error. 

I am using the `i3` window manager on barebones arch linux system. I would be interested to know if other tiling managers like `dwm` experience the same issue.

Floating windows using gtk and the like do not experience the same issue.

**Comment by lokedhs** [comment] 2019-01-24 04:36
The same thing happens on Qubes OS. As best as I can tell, the reason is that there is code that assumes that the windows are reparented inside another window that holds window decorations. In Qubes OS, and also tiling window managers, this assumption doesn't hold, and the application window is relative to the root window. 

A related bug was fixed some time ago that caused the menus to move to the wrong location.

**Comment by scymtym** [comment] 2019-01-24 08:51
This is a duplicate of #499.

**Closed** 2019-01-24 08:51 UTC
Labels: duplicate
