### ISSUE TITLE
Incongruent Lambda lists in ECL 16 - OpenBSD SPARC64

### ISSUE THREAD

**Issue by abuhussain** [McCLIM/McCLIM#1076] opened 2020-09-28 14:35 UTC
I came across this interesting error message while trying to compile the latest (20200925) Mcclim available on Quicklisp on the mentioned platform:

ASDF could not load mcclim because
Cannot add the method #<standard-method UNNAMED (|(presentation-type COMMON-LISP::NULL)|
                                                                                         T T
                                                                                         TEXTUAL-VIEW)> to the generic function
                                                                                         #<presentation-generic-function %ACCEPT> because their lambda lists
                                                                                      (type-key type stream view &key default default-type &allow-other-keys)
                                                                                       and
                                                                                      (type-key type stream view &key)
                                                                                       are not congruent...

Although the error message is relatively verbose, I don't have enough experience with mcclim to be able to point out any 'anomaly' or 'feature' which could be causing this behaviour in this particular platform - Any insights much appreciated.

**Comment by dkochmanski** [comment] 2020-09-28 14:58
Thanks for the report. This was a bug in ECL (which I have fixed in the newest release). You may check out the merge request here: https://gitlab.com/embeddable-common-lisp/ecl/-/merge_requests/194 and a discussion in there for more information (basically it is somewhat vague wording in the common lisp specification -- ECL adopted a more permissive approach).

Since the issue is already addressed, I'm closing this ticket.

**Closed by dkochmanski** 2020-09-28 14:58 UTC

**Comment by abuhussain** [comment] 2020-09-28 15:28
thanks @dkochmanski , so if I understood you well that means that this problem isn't present in ECL20?

**Comment by dkochmanski** [comment] 2020-09-28 16:05
yes. for the record, in bug reports please use the full version (i.e there were two releases with a major number 16 (16.1.2 and 16.1.3), so that would be ECL 20.4.24
