### ISSUE TITLE
list-pane and option-pane: selecting an item makes it invisible

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#650] opened 2018-12-31 11:29 UTC
If you click to select an item which isn't the first one in a list-pane or an option-pane, the item becomes invisible. Additionally, in an option pane, just moving the mouse over an item makes it invisible. An item becomes visible again when another is selected - which in turn becomes invisible. The bug can be seen in List Test and Option Test in clim-examples, and in the code snippet below. In the screenshot the second items have been selected.

This seems to be a highlighting problem. There do not seem to have been any relevant recent changes to gadgets.lisp, so I guess the problem is somewhere else.

This is with mcclim-20181210-git and clx-20181210-git

```
(in-package :clim-user)

(define-application-frame optiontest ()
  ()
  (:menu-bar t)
  (:panes
    (p5 
      (make-pane 'list-pane
        :value "P5 item 1"
        :items '("P5 item 1" "P5 item 2" "P5 item 3")))
    (p6 
      (make-pane 'option-pane
        :value "P6 option 1"
        :items '("P6 option 1" "P6 option 2" "P6 option 3"))))
 (:layouts
    (default
      (spacing (:thickness 20)
        (vertically (:y-spacing 20) p5 p6)))))
               
(defun optiontest ()
  (run-frame-top-level (make-application-frame 'optiontest :width 250)))

(define-optiontest-command (quit :name t :menu t) ()
  (with-application-frame (frame) (frame-exit frame)))

(optiontest)
```

![optiontest-screenshot](https://user-images.githubusercontent.com/31476017/50559457-33f63000-0cef-11e9-8302-4cc1beb094ac.png)

**Comment by admich** [comment] 2018-12-31 18:08
I had the same bug with a version of sbcl (i don't remember which one). Now with sbcl 1.4.13 I don't have this bug. So it'is a very strange bug that depend on the lisp implementation.

**Comment by slyrus** [comment] 2018-12-31 23:43
This might be the same as Issue #633.

**Comment by john-a-carroll** [comment] 2019-01-01 11:42
I observed the problem when running in SBCL 1.4.14. Following up on the comment of admich, I've just tried SBCL 1.4.13 and Clozure CL 1.11, and this bug is not evident with either of them.

**Comment by nsrahmad** [comment] 2019-01-02 03:46
with SBCL 1.4.15, I can't reproduce either. Closing it for now, If you encounter something similar again, feel free to re-open this.

**Closed by nsrahmad** 2019-01-02 03:46 UTC
