### ISSUE TITLE
"slide-out effect": Displacement of frame contents when window is moved off-screen

### ISSUE THREAD

**Issue by dg1sbg** [McCLIM/McCLIM#538] opened 2018-09-01 05:44 UTC
[slide-out-mcclim.m4v.zip](https://github.com/McCLIM/McCLIM/files/2342091/slide-out-mcclim.m4v.zip)

**Comment by nsrahmad** [comment] 2018-09-01 05:49
Its duplicate of #499

**Comment by dg1sbg** [comment] 2018-09-01 06:07
Sorry - missed #499.

**Closed** 2018-09-01 06:07 UTC
Labels: duplicate
