### ISSUE TITLE
check-box and radio-box are not displayed

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#946] opened 2020-01-20 09:03 UTC
After the last PR #940  the check-box and the radio-box are not displayed anymore.

**Comment by dkochmanski** [comment] 2020-01-20 09:21
Issue is caused by a commit e7dd0930 `gadgets: simplify superclass lists of {SLIDER,{RADIO,CHECK}-BOX}-PANE`

**Comment by dkochmanski** [comment] 2020-01-20 09:25
quick fix is to reverse removal of basic-pane from the superclasses (as a direct superclass):

```
diff --git a/Core/clim-core/gadgets/concrete.lisp b/Core/clim-core/gadgets/concrete.lisp
index 19d6ad9a..3faf87c8 100644
--- a/Core/clim-core/gadgets/concrete.lisp
+++ b/Core/clim-core/gadgets/concrete.lisp
@@ -596,7 +596,8 @@
 (defclass slider-pane (slider
                        gadget-color-mixin
                        value-changed-repaint-mixin
-                       activate/deactivate-repaint-mixin)
+                       activate/deactivate-repaint-mixin
+                       basic-pane)
   ())
 
 (defmethod compose-space ((pane slider-pane) &key width height)
@@ -770,7 +771,8 @@
                           rack-layout-mixin
                           activate/deactivate-repaint-mixin
                           sheet-multiple-child-mixin
-                          activate/deactivate-children-mixin)
+                          activate/deactivate-children-mixin
+                          basic-pane)
   ()
   (:default-initargs :background *3d-normal-color*))
 
@@ -804,7 +806,7 @@
                           rack-layout-mixin
                           activate/deactivate-repaint-mixin
                           sheet-multiple-child-mixin
-                          activate/deactivate-children-mixin)
+                          basic-pane)
   ()
   (:default-initargs :background *3d-normal-color*))
```

I'm going to first find why this causes the regression before reverting the change.

**Comment by dkochmanski** [comment] 2020-01-20 09:54
OK, the gist of the problem is this:

1. method `sheet-children` has a specialization on `basic-pane` to return NIL (it is wrong, because it should be `sheet-leaf-mixin` specialization, but numerous panes does not have it as a superclass so removing it would be correct still will break many things, so better to have it in a bigger PR.

2. sheet-multiple-child-mixin has method sheet-children alright and sheet-adopt-child method defiend as follows:

(defmethod sheet-adopt-child ((sheet sheet-multiple-child-mixin)
			      (child sheet-parent-mixin))
  (push child (sheet-children sheet)))

so if basic-sheet is higher in the class precedence list than sheet-multiple-child-mixin, then sheet-adopt-child pushes to nil instead of the slot. that's why basic-pane must be (in cases above) *after* `sheet-multiple-child-mixin`.

Another way to mitigate the issue (still the problem with sheet-children returning incorrect value remains), is to implement sheet-adopt-child on sheet-multiple-child-mixin that it pushes to the slot-value instead of the accessor invocation.

@scymtym

**Comment by dkochmanski** [comment] 2020-01-20 10:05
removing `sheet-adopt-child` specialization from `basic-sheet` just masked the issue. I think that primary methods on basic-sheet should signal an error if the protocol does not belong to the basic-sheet, so it is apparent at the first glance that something is not right.

**Comment by dkochmanski** [comment] 2020-01-20 10:38
![obraz](https://user-images.githubusercontent.com/6871201/72719904-148ba880-3b79-11ea-82b4-abaa02b18e82.png)

gadgets in red color are not part of window hierarchy protocol (i.e scroll-bar-pane). Experiment with code below to examine other basic-sheet subclasses. Code should be extedned to check, if basic-sheet is higher in the precedence list to show, where we may stomp on the problem (I need to go now, so I'm leaving this snippet incomplete for now).

```
(slim:defapp show-sheet-mixins (sheet-class)
  (format-graph-from-roots
   (list sheet-class)
   (lambda (object stream)
     (with-drawing-options
         (stream :text-face (if (subtypep object 'sheet-parent-mixin)
                                :bold
                                :italic)
                 :ink (cond
                        ((subtypep object 'sheet-leaf-mixin)           +dark-blue+)
                        ((subtypep object 'sheet-single-child-mixin)   +dark-olive-green+)
                        ((subtypep object 'sheet-multiple-child-mixin) +dark-green+)
                        (t                                             +dark-red+)))
       (format stream "~a" (class-name object))))
   #'c2mop:class-direct-subclasses))
```

**Comment by dkochmanski** [comment] 2020-01-20 13:10
Here is a more complete picture (of our core system, without examples). Green and blue sheets are fine. Red sheets do not subclass neither child nor leaf mixin, what is wrong in case of classes which are meant to have an instance (scroll-bar-pane, generic-list-pane, slider-pane etc).

Pink nodes are a disaster: basic-sheet protocol takes precedence over the child mixin.
![obraz](https://user-images.githubusercontent.com/6871201/72728853-9a661e80-3b8e-11ea-9ca3-bc7a025f50f3.png)


```

(in-package clim-user)
(slim:defapp show-sheet-mixins (sheet-class)
  (format-graph-from-roots
   (list sheet-class)
   (lambda (object stream)
     (with-drawing-options
         (stream :text-face (if (subtypep object 'sheet-parent-mixin)
                                :bold
                                :italic)
                 :ink (cond
                        ((and (subtypep object '(or
                                                 sheet-leaf-mixin
                                                 sheet-single-child-mixin
                                                 sheet-multiple-child-mixin
                                                 sheet-parent-mixin))
                              (alexandria:when-let
                                  ((cpl (ignore-errors
                                         (c2mop:class-precedence-list object))))
                                (< (position (find-class 'basic-sheet) cpl)
                                   (or (position (find-class 'sheet-leaf-mixin) cpl)
                                       (position (find-class 'sheet-single-child-mixin) cpl)
                                       (position (find-class 'sheet-multiple-child-mixin) cpl)
                                       (position (find-class 'sheet-parent-mixin) cpl)))))
                         +violet+)
                        ((subtypep object 'sheet-leaf-mixin)           +dark-blue+)
                        ((subtypep object 'sheet-single-child-mixin)   +dark-olive-green+)
                        ((subtypep object 'sheet-multiple-child-mixin) +dark-green+)
                        (t                                             +dark-red+)))
       (format stream "~a" (class-name object))))
   #'c2mop:class-direct-subclasses
   :merge-duplicates t
   :maximize-generations t
   ))

(show-sheet-mixins (find-class 'clim:basic-sheet))
(show-sheet-mixins (find-class 'clim:sheet-single-child-mixin))
(show-sheet-mixins (find-class 'clim:sheet-multiple-child-mixin))
```

**Comment by dkochmanski** [comment] 2020-01-20 16:59
I've made a pull request which addresses the problem in all classes which exist in Core

https://github.com/McCLIM/McCLIM/pull/947

It doesn't touch demos and only slightly curates extensions.

**Comment by scymtym** [comment] 2020-01-20 17:19
I think we should try to make the order of `basic-gadget` and the various mixins not matter instead of making the ordering constraint "official".

If we go with the constraint, in my opinion it should be checked at `defclass`-time, not when an attempt is made to use the incorrectly implemented protocol.

**Comment by dkochmanski** [comment] 2020-01-20 17:30
I don't know how that could be achieved, because spec clearly says, that each sheet must have sheet-children and sheet-parent methods implemented. IMO first let's fix the problem we have and then we may think about further improvements. Reintroducing the canary method is uncontroversial because it is not something new but rather recently removed method which is, nomen omen, correct  -- basic-sheet don't know how to adopt other sheets.

**Comment by scymtym** [comment] 2020-01-20 20:39
Wouldn't something like this work?

```lisp
(in-package #:climi)

(defun map-concrete-classes (function root)
  (let ((seen (make-hash-table :test #'eq)))
    (labels ((rec (class)
               (unless (gethash class seen)
                 (setf (gethash class seen) t)
                 (if-let ((subclasses (c2mop:class-direct-subclasses class)))
                   (mapc #'rec subclasses)
                   (funcall function class)))))
      (rec root))))

(defun implements-sheet-protocol-p (class)
  (c2mop:ensure-finalized class)
  (labels ((primaryp (method)
             (null (method-qualifiers method)))
           (suitable-method-p (generic-function &rest other-arguments)
             (let* ((arguments (list* (c2mop:class-prototype class)
                                      other-arguments))
                    (methods (compute-applicable-methods
                              generic-function arguments)))
               (remove-if-not #'primaryp methods))))
    (suitable-method-p #'sheet-adopt-child (c2mop:class-prototype (find-class 'sheet-parent-mixin)))))

(map-concrete-classes
 (lambda (class)
   (with-simple-restart (continue "Next")
     (unless (implements-sheet-protocol-p class)
       (print class))))
 (find-class 'basic-sheet))
```

I think this could be used to find incomplete protocol implementations at compile-time.

Regarding runtime errors, there are methods for `sheet-leaf-mixin` which signal appropriate errors. That seems more suitable than `basic-sheet` methods.

**Comment by dkochmanski** [comment] 2020-01-20 21:08
this will show only problems with sheet-adopt-child, not classes which have malformed precedence order. e.g sheet-children and sheet-parent may be taken from the basic-sheet class while they have more suitable implementation in one of their mixins. snippet above (and a screenshot) already shows classes which exhibit such behavior.

The problem is not that error is not signaled for sheet-leaf-mixin, the problem is that sheet-children returns NIL after multiple sheet-adopt-child returns nil for sheet-multiple-children-mixin, because of the wrong CPL order. Problem passes silently, because basic-sheet doesn't complain. Sanitizing at compile time is not a bad idea, but it won't solve the problem, only tell us something what we already know. #947 fixes the regression.

We could take a pedantic interpretation and assert, that classes which inherit only from the basic-sheet must take a full set of mixins or implement all methods themself, but that defeats a purpose of having a basic-sheet implementing a "default behavior". Also I'm sure it would break code in the wild given we did rely on that in our own demos too.

**Comment by scymtym** [comment] 2020-01-20 22:39
> This will show only problems with sheet-adopt-child, not classes which have malformed precedence order.

I would argue the problem is the fact that there can be such a thing as a "malformed" precedence list. Or in other words, a default method that has inappropriate behavior in certain cases may do more harm than good. Especially given the fact that there are mixin classes for the three typical behaviors (no children, one child, multiple children).

> snippet above (and a screenshot) already shows classes which exhibit such behavior.

As I understand it, the difference is that the graph is based on the mixin classes while using `compute-applicable-methods` would also recognize classes that do not use the mixins.

> The problem is not that error is not signaled for sheet-leaf-mixin, the problem is that sheet-children returns NIL after multiple sheet-adopt-child for sheet-multiple-children-mixin, because of the wrong CPL order. Problem passes silently, because basic-sheet doesn't complain.

I don't understand this explanation. Are you also saying the `basic-sheet` default methods are the problem? 

> Sanitizing at compile time is not a bad idea, but it won't solve the problem, only tell us something what we already know.

We know this about the code as it is now, but statically asserting the properties required by the protocol allows changing things without worrying about losing the correctness of the protocol implementation. Same relation as between trying things once in the REPL and automatic unit or regression tests.

> We could take a pedantic interpretation and assert, that classes which inherit only from the basic-sheet must take a full set of mixins or implement all methods themself, but that defeats a purpose of having a basic-sheet implementing a "default behavior".

I tend to think that would be the correct solution, actually. Also "defeats the purpose" is a little exaggerated since `basic-sheet` appears as a specializer in around 70 methods and we are talking about removing maybe three.

**Comment by dkochmanski** [comment] 2020-01-21 08:13
Here is my perspective:
Recent changes caused a regression which we need to fix. The way to address a regression is to work better with what we have now (that is - that cpl is relevant).

**After** that we may think how to remove this particular "gotcha" so future contributors won't be able to make such mistake -- in a separate ticket and with a separate PR. "Just" removing basic-sheet methods now won't work now because of other gadgets not having a windowing mixin (i.e scroll bar gadget) - that problem is also fixed in the PR, so after merging it it will be less troublesome to remove methods specialized on basic-sheet if we really decide to do so.

**Closed** 2020-01-21 15:34 UTC
Labels: bug
