### ISSUE TITLE
guided-tour examples

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#47] opened 2016-07-08 07:35 UTC
Verify which Guide-Tour examples from the manual doesn't work and fix them (for instance hello-world does load clim and clim-clx, but it should load mcclim system).

**Comment by jane-lx** [comment] 2019-02-02 06:11
Tested with latest quicklisp mcclim and clx on SBCL 1.4.13.

The hello-world example does not appear to work.

``` lisp
(in-package :common-lisp-user)

(defpackage "HELLO-WORLD" (:use :clim :clim-lisp) (:export hello-world-main))

(in-package :hello-world)

(define-application-frame hello-world ()
  ((greeting :initform "Hello world"
             :accessor greeting))
  (:pane (make-pane 'hello-world-pane)))

(defclass hello-world-pane
    (clim-stream-pane) ())

(defmethod handle-repaint ((pane hello-world-pane) region)
  (let ((w (bounding-rectangle-width pane))
        (h (bounding-rectangle-height pane)))
    ;; Blank the pane out
    (draw-rectangle* pane 0 0 w h
                     :filled t
                     :ink (pane-background pane))
    ;; Draw greeting in center of pane
    (draw-text* pane
                (greeting *application-frame*)
                (floor w 2) (floor h 2)
                :align-x :center
                :align-y :center)))

(defun hello-world-main ()
  (run-frame-top-level (make-application-frame 'hello-world)))
```
```
(hello-world:hello-world-main)

WINDOW-ERROR in current request  Code 3.0 [GetWindowAttributes] ID #x100002C
   [Condition of type XLIB:WINDOW-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 4: #<CLOSURE (LABELS SWANK/SBCL::RUN :IN SWANK/BACKEND:ADD-FD-HANDLER) {100460A8FB}>>
 3: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: (XLIB::X-ERROR XLIB:WINDOW-ERROR :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R12003000)> :ERROR-KEY XLIB:WINDOW-ERROR :ASYNCHRONOUS NIL :CURRENT-SEQUENCE 921 :RESOURCE-ID 16777260 :MAJOR 3 :MINOR..
  1: (XLIB::READ-REPLY #<XLIB:DISPLAY :0 (The X.Org Foundation R12003000)> #S(XLIB::PENDING-COMMAND :SEQUENCE 921 :REPLY-BUFFER NIL :PROCESS #<SB-THREAD:THREAD "main thread" RUNNING {10005185B3}> :NEXT NIL..
  2: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB::GET-WINDOW-ATTRIBUTES-BUFFER))
  3: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
  4: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB::GET-WINDOW-ATTRIBUTES-BUFFER) {7F560715646B}> #<SB-THREAD:MUTEX "CLX Buffer Lock" owner: #<SB-THREAD..
  5: (XLIB::GET-WINDOW-ATTRIBUTES-BUFFER #<XLIB:WINDOW :0 100002C>)
  6: (XLIB:WINDOW-EVENT-MASK #<XLIB:WINDOW :0 100002C>)
  7: ((:METHOD CLIM:ADOPT-FRAME :AFTER (CLIM-CLX::CLX-FRAME-MANAGER CLIM:APPLICATION-FRAME)) #<unused argument> #<HELLO-WORLD::HELLO-WORLD {100253D333}>) [fast-method]
  8: ((SB-PCL::EMF CLIM:ADOPT-FRAME) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-FRAME-MANAGER {1004FECD73}> #<HELLO-WORLD::HELLO-WORLD {100253D333}>)
  9: ((:METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)) #<HELLO-WORLD::HELLO-WORLD {100253D333}>) [fast-method]
 10: (SB-INT:SIMPLE-EVAL-IN-LEXENV (HELLO-WORLD:HELLO-WORLD-MAIN) #<NULL-LEXENV>)
 11: (EVAL (HELLO-WORLD:HELLO-WORLD-MAIN))
 --more--
```

Whereas the quickdocs example does work on the same setup.
``` lisp
(in-package :common-lisp-user)

(defpackage :app (:use :clim :clim-lisp) (:export app-main))

(in-package :app)

(define-application-frame superapp () ()
  (:panes (int :interactor :height 400 :width 600))
  (:layouts (default int)))

(defun app-main ()
  (run-frame-top-level (make-application-frame 'superapp)))
```

**Comment by jane-lx** [comment] 2019-02-02 07:20
Umm, so there's one change to make it work:
``` lisp
(defclass hello-world-pane
    (clim-stream-pane) ())
```
becomes
``` lisp
(defclass hello-world-pane
    (basic-pane) ())
```

I don't know what the implications are and whether it's indicative of a bug that it doesn't work to inherit from clim-stream-pane. But maybe it wouldn't hurt to change the example? Unless there is an aspect of clim-stream-pane that is useful for edification?

**Comment by jane-lx** [comment] 2019-02-04 05:08
Okay I think this is a confirmed bug because writing it like this still changes the medium ink to black when the lines are draw:
``` lisp
(defmethod handle-repaint ((pane draw-pane) region)
  (with-application-frame (frame)
    (call-next-method)
    (with-drawing-options (pane :ink +black+))
    (dolist (line (lines frame))
      (draw-line pane (car line) (cdr line)))
    (dolist (pair (strings frame))
      (draw-text pane (cdr pair) (car pair)))))
```

**Comment by nsrahmad** [comment] 2019-10-06 06:08
Fixed with https://github.com/McCLIM/McCLIM/pull/806

**Closed by nsrahmad** 2019-10-06 06:08 UTC
Labels: enhancement
